package utility;
public enum Permissions {
	CREATE_FORUM,
	SET_FORUM_PROPERTIES,
	CREATE_SUB_FORUM,
	CREATE_MESSAGE,
	SET_RANKS,
	SET_USER_RANK,
	DELETE_MESSAGE,
	DELETE_SUB_FORUM,
	ADD_ADMIN,
	REMOVE_ADMIN,
	ADD_MODERATOR,
	REMOVE_MODERATOR
}
