package utility;
public enum PolicyRules {
	//MSG DELETION
	ONLY_AUTHOR_DELETES_MSG,
	ONLY_ADMIN_DELETES_MSG,
	MODERATOR_CAN_DELETE_MSG,
	//MODERATOR ADDITION
	MODERATOR_NEEDS_X_MSGS,
	MODERATOR_NEEDS_X_VETERANSHIP,
	//MODERATOR REMOVAL
	ONLY_PROMOTER_REMOVES,
	CANT_REMOVE_SINGLE_MODERATOR,
	
	//SIGN UP AND SIGNING IN POLICY
	
	QUESTIONS_IN_ADDITION_TO_PASSWORD,
	
	//INTERACTIVENESS
	ONLINE_NOTIFICATIONS,
	OFFLINE_NOTIFICATIONS,
	SELECTIVE_NOTIFICATIONS,
	
	//MSG CONTENT POLICY
	
}
